apiVersion:apps/v1
kind: Deployment
metadate:
  name: hello-deployment
  spec:
    replicas:3
    selector:
      matchLabls:
        app:python-print
      template:
        metadate:
          labels:
            app: python-print
  spec:
    containers:
    - name: python-container
    image: khbin501/hello-pod:v1
